openapi: 3.0.0
info:
  title: WorkerSense API
  description: Access real-time wearable-driven project insights with the WorkerSense
    API.
  version: Alpha
servers:
- url: https://api.workersense.com
paths:
  /oauth/token:
    post:
      tags:
      - Authentication
      summary: Get Or Refresh An Access Token
      description: |-
        Used to acquire a new access token or refresh an existing access token. Certain parameter combinations and values are used depending on which scenario you are handling.

        **Basic Authorization header containing your WorkerSense account email and password is required only for "password" grant types.**
      operationId: oauthTokenPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
            examples:
              Password:
                value:
                  grant_type: password
              Refresh Token:
                value:
                  grant_type: refresh_token
                  refresh_token: AGEhc0DQFS5xBUkPIkOfaiM_QBolN_zOMhakvUjZUN78haRlagzEwgPlgUzKawPwoJ0FAt9knwcsRCjK-fG9uifiDYC78F0tcVRd0aFkmG_RXsdK7dujPusJd1UyWuqKs_ap70-uWWb_jae-go0GDiMMkQHQ5MirhwvXlPOjDl16hk7FOQqHQKl7pU9q0nL9Sjf1vcxq6zANbxo0csS-ucHLBZjBRnjD-Q
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
              example:
                access_token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNjM2Y0ZThiMmYxZDAyZjBlYTRiMWJkZGU1NWFkZDhiMDhiYzUzODYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vd29ya2Vyc2Vuc2UiLCJhdWQiOiJ3b3JrZXJzZW5zZSIsImF1dGhfdGltZSI6MTYyMDcwNDIzNywidXNlcl9pZCI6IjlHdjRNVUt2UURoY292RklDSXRWdnRQWXVqMTIiLCJzdWIiOiI5R3Y0TVVLdlFEaGNvdkZJQ0l0VnZ0UFl1ajEyIiwiaWF0IjoxNjIwNzQyNzAyLCJleHAiOjE2MjA3NDYzMDIsImVtYWlsIjoiY2FueW9uQHdvcmtlcnNlbnNlLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIdpwImNhbnlvbkB3b3JrZXJzZW5zZS5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.h6pKDygoZW7mkrr1m2OmVpjE1iWrnxjbNw83dR7sY6NfQCmwwX8JOgV0Gcb0nGudFLpp9pxweJanSVIXEz2i6LPfY_VTV_YaLmyB_rNHkZ7-xWweJpmaluvtnuHCm4gBrG_f5Rs5xp4zzOkczWqyM51JPgkpaze7JGTGHPskqF_PnF3JHn3egLss6G_xUtsI4hxlrEaiIfZS3O15RTUXLYeAYtQYoRxZ7eMCrSj19865JtMw3p0rZOVSpVq5OxNFgoUp38RwfgO49DXGKnvLVGUy28_fOs_IkERApKkN42rSDM_MePdhlskl0abP-1AH-3b4jiQov1mdsIQA9WcxPQ
                refresh_token: AGEhc0DQFS5xBUkPIkOfaiM_QBolN_zOMhakvUjZUN78haRlagzEwgPlgUzKawPwoJ0FAt9knwcsRCjK-fG9czfiDYC78F0tcVRd0aFkmG_RXsdK7fpwPusJd1UyWuqKs_ap70-uWWb_jae-go0GDiMMkQHQ5MirhwvRlPOjDl59hk7FOQqHQKl7pU9q0nL1Sjf1vcxq6zANbxo0csS-ucHLBZjBRnjD-Q
                token_type: bearer
                expires: 3600
      security:
      - {}
      - BasicAuth: []
      x-swagger-router-controller: Authentication
  /projects:
    get:
      tags:
      - Portfolio
      summary: List Projects
      description: Return a list of projects the user has been added to.
      operationId: projectsGET
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
                x-content-type: application/json
              example:
              - client: WJR1fb2dx7dEqFwT0vNM
                project: lzPBZLDEnHp9h13VHxm7
                name: Simulator Site
                city: Los Angeles
                state: CA
                lon: -118.253248
                lat: 34.050064
                progression: 0.683279902
                start: 1483300814000
      security:
      - BearerAuth: []
      x-swagger-router-controller: Portfolio
    post:
      tags:
      - Portfolio
      summary: Create Project
      description: Create a new project within a WorkerSense client account.
      operationId: projectsPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_1'
            example:
              name: Sample Construction Project
              address_1: 555 W 5th St
              address_2: 35th Floor
              city: Los Angeles
              state: CA
              zip: "90013"
              country: United States
              start: 1620935064000
              end: 1639267200000
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
              example:
                success: true
                id: 6lenfgcbLDns9Avbn8z8
      security:
      - BearerAuth: []
      x-swagger-router-controller: Portfolio
  /projects/{project}/companies:
    get:
      tags:
      - Project Directory
      summary: Show Project Companies
      description: "Return a list of all companies (vendors, subcontractors, etc)\
        \ included within the project directory."
      operationId: projectsProjectCompaniesGET
      parameters:
      - name: project
        in: path
        description: Unique ID of the project
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_3'
                x-content-type: application/json
              example:
              - name: Santa Monica Drywall
                id: LqRIXJlk5z7czKLNv5ML
                address_1: 1133 9th St
                address_2: ""
                city: Santa Monica
                state: CA
                zip: "90403"
                country: United States
                phone: +13103020019
      security:
      - BearerAuth: []
      x-swagger-router-controller: ProjectDirectory
    post:
      tags:
      - Project Directory
      summary: Add a Company
      description: "Add a company (vendor, subcontractor, etc) to a project."
      operationId: projectsProjectCompaniesPOST
      parameters:
      - name: project
        in: path
        description: Unique ID of the project
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_2'
            example:
              name: Santa Monica Drywall
              address_1: 1133 9th St
              address_2: ""
              city: Santa Monica
              state: CA
              zip: "90403"
              country: United States
              phone: +13103020019
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
              example:
                success: true
                id: LqRIXJlk5z7czKLNv5ML
      security:
      - BearerAuth: []
      x-swagger-router-controller: ProjectDirectory
  /projects/{project}/users:
    get:
      tags:
      - Project Directory
      summary: Show Project Users
      description: Return a list of all users (management personnel) included within
        the project directory.
      operationId: projectsProjectUsersGET
      parameters:
      - name: project
        in: path
        description: Unique ID of the project
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_5'
                x-content-type: application/json
              example:
              - name: Ada Lovelace
                id: 2OImMD9zR9tvkeFEOmoO
                first: Ada
                last: Lovelace
                initials: AL
                cell_phone: +13104590188
                email: ada@workersense.com
                city: Los Angeles
                state: CA
                zip: "90013"
                country: United States
                created: 1612883478000
                logged_in: true
                assigned_mount: false
                mount_id: ""
                company:
                  name: "WorkerSense, Inc"
                  id: WJR1fb2dx7dEqFwT0vNM
                permissions:
                  anonymized_individuals: false
                  company_only_visibility: false
                  dashboard_access:
                  - dashboard_main
                  - production
                  - health_and_safety
                  - integrations
                  - reports
                  - automation
                  - fleet
                  - admin
                  - billing
      security:
      - BearerAuth: []
      x-swagger-router-controller: ProjectDirectory
    post:
      tags:
      - Project Directory
      summary: Add a User
      description: Add a user (management personnel) to a project.
      operationId: projectsProjectUsersPOST
      parameters:
      - name: project
        in: path
        description: Unique ID of the project
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_3'
            example:
              company: WJR1fb2dx7dEqFwT0vNM
              first: Ada
              last: Lovelace
              email: ada@workersense.com
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
              example:
                success: true
                id: 2OImMD9zR9tvkeFEOmoO
      security:
      - BearerAuth: []
      x-swagger-router-controller: ProjectDirectory
  /projects/{project}/workers:
    get:
      tags:
      - Project Directory
      summary: Show Project Workers
      description: Return a list of all workers included within the project directory.
      operationId: projectsProjectWorkersGET
      parameters:
      - name: project
        in: path
        description: Unique ID of the project
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_7'
                x-content-type: application/json
              example:
              - name: Tom Cruise
                id: hXIZZ8HIdjn29EdX8OvB
                first: Tom
                last: Cruise
                initials: TC
                cell_phone: +13109412384
                email: ""
                city: Los Angeles
                state: CA
                zip: "90013"
                country: United States
                created: 1612883478000
                assigned_mount: true
                mount_id: "901345"
                last_seen: 1620944836000
                on_site: false
                company:
                  name: "WorkerSense, Inc"
                  id: WJR1fb2dx7dEqFwT0vNM
      security:
      - BearerAuth: []
      x-swagger-router-controller: ProjectDirectory
    post:
      tags:
      - Project Directory
      summary: Add a Worker
      description: Add a worker to a project.
      operationId: projectsProjectWorkersPOST
      parameters:
      - name: project
        in: path
        description: Unique ID of the project
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_4'
            example:
              first: Tom
              last: Cruise
              cell_phone: +13109412384
              company: WJR1fb2dx7dEqFwT0vNM
              mount_id: "901345"
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_8'
              example:
                success: true
                id: hXIZZ8HIdjn29EdX8OvB
      security:
      - BearerAuth: []
      x-swagger-router-controller: ProjectDirectory
  /projects/timecards:
    post:
      tags:
      - Operations
      summary: Show Project Timecards
      description: Return detailed timecard information for all companies on site
        for a selected day.
      operationId: projectsTimecardsPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_5'
            example:
              client: WJR1fb2dx7dEqFwT0vNM
              project: lzPBZLDEnHp9h13VHxm7
              date: 2021-05-12
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_9'
                x-content-type: application/json
              example:
              - name: "WorkerSense, Inc"
                id: WJR1fb2dx7dEqFwT0vNM
                on_site: true
                headcount: 1
                arrival_local: 6:44 AM
                arrival_unix: 1620827055000
                workers:
                - name: John Appleseed
                  id: vjaXfl5Jq5EM2OQEssrc
                  on_site: true
                  arrival_local: 6:44 AM
                  arrival_unix: 1620827055000
                  exit_local: ""
                  exit_unix: 0
                  duration: 272.6
      security:
      - BearerAuth: []
      x-swagger-router-controller: Operations
  /projects/risk:
    post:
      tags:
      - Health and Safety
      summary: Show Project Risk Factors
      description: Return detailed risk assessment information for all workers on
        site for a selected day.
      operationId: projectsRiskPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_6'
            example:
              client: WJR1fb2dx7dEqFwT0vNM
              project: lzPBZLDEnHp9h13VHxm7
              date: 2021-05-12
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_10'
                x-content-type: application/json
              example:
              - risk: Fall Risk
                id: fall_risk
                headcount: 1
                workforce_percentage: 1
                change: 1
                trend: higher
                workers:
                - name: John Appleseed
                  id: vjaXfl5Jq5EM2OQEssrc
                  duration: 39.184
                  day_percentage: 0.94047
      security:
      - BearerAuth: []
      x-swagger-router-controller: HealthAndSafety
  /projects/workforce:
    post:
      tags:
      - Operations
      summary: Show Project Workforce Composition
      description: Return workforce composition information for all subcontractors
        on site for a selected day.
      operationId: projectsWorkforcePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_7'
            example:
              client: WJR1fb2dx7dEqFwT0vNM
              project: lzPBZLDEnHp9h13VHxm7
              date: 2021-05-12
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_11'
              example:
                peak_total_manpower: 1
                subcontractors:
                - name: "WorkerSense, Inc"
                  id: WJR1fb2dx7dEqFwT0vNM
                  headcount: 1
                  workforce_percentage: 1
                  change: 1
                  trend: higher
                  workers:
                  - name: John Appleseed
                    id: vjaXfl5Jq5EM2OQEssrc
                    on_site: true
                    arrival_local: 6:44 AM
                    arrival_unix: 1620827055000
      security:
      - BearerAuth: []
      x-swagger-router-controller: Operations
  /projects/zones:
    post:
      tags:
      - Operations
      summary: Show Project Work Zones
      description: Return detailed location analysis for all workers on site for a
        selected day.
      operationId: projectsZonesPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body_8'
            example:
              client: WJR1fb2dx7dEqFwT0vNM
              project: lzPBZLDEnHp9h13VHxm7
              date: 2021-05-12
        required: true
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_12'
                x-content-type: application/json
              example:
              - name: Building C (Scaffolding)
                id: 500099
                total_time: 88.78399
                location:
                - Building C
                - West Side
                - Scaffolding
                hazards:
                - fall_risk
                ppe:
                - tie_off
                certifications:
                - working_at_height
                production:
                - activity_id: W23756
                  activity_name: Window Installation
                  activity_rate: 1.25
                  company_id: WJR1fb2dx7dEqFwT0vNM
                  cost_code: ""
                traffic:
                - name: "WorkerSense, Inc"
                  id: WJR1fb2dx7dEqFwT0vNM
                  total_time: 88.78399
                  workers:
                  - name: John Appleseed
                    id: vjaXfl5Jq5EM2OQEssrc
                    total_time: 88.78399
      security:
      - BearerAuth: []
      x-swagger-router-controller: Operations
components:
  schemas:
    projectsrisk_workers:
      type: object
      properties:
        name:
          type: string
          description: returns worker's full name
        id:
          type: string
          description: returns unique ID of worker
        duration:
          type: number
          description: "returns in minutes, duration of time spent exposed to present\
            \ risk factor for selected date"
        day_percentage:
          type: number
          description: returns percentage of day spent exposed to present risk factor
            for selected date
      example:
        duration: 5.962133916683182377482808078639209270477294921875
        day_percentage: 5.63737665663332876420099637471139430999755859375
        name: name
        id: id
    inline_response_200_11:
      type: object
      properties:
        peak_total_manpower:
          type: integer
          description: returns peak manpower for selected date
        subcontractors:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_11_subcontractors'
      example:
        peak_total_manpower: 0
        subcontractors:
        - headcount: 6
          trend: trend
          change: 1.46581298050294517310021547018550336360931396484375
          name: name
          id: id
          workers:
          - name: name
            id: id
            arrival_local: arrival_local
            on_site: true
            arrival_unix: 5
          - name: name
            id: id
            arrival_local: arrival_local
            on_site: true
            arrival_unix: 5
        - headcount: 6
          trend: trend
          change: 1.46581298050294517310021547018550336360931396484375
          name: name
          id: id
          workers:
          - name: name
            id: id
            arrival_local: arrival_local
            on_site: true
            arrival_unix: 5
          - name: name
            id: id
            arrival_local: arrival_local
            on_site: true
            arrival_unix: 5
    inline_response_200_10:
      type: object
      properties:
        risk:
          type: string
          description: returns name of present risk factor
        id:
          type: string
          description: returns id of present risk factor
        headcount:
          type: integer
          description: returns total number of workers exposed to present risk factor
            for selected date
        workforce_percentage:
          type: number
          description: returns percentage of total workforce exposed to present risk
            factor for selected date
        change:
          type: number
          description: returns percentage difference in workforce exposure to present
            risk factor relative to previous date
        trend:
          type: string
          description: returns trend of percentage difference in workforce exposure
            to present risk factor relative to previous date
        workers:
          type: array
          items:
            $ref: '#/components/schemas/projectsrisk_workers'
      example:
        headcount: 0
        trend: trend
        change: 1.46581298050294517310021547018550336360931396484375
        risk: risk
        id: id
        workforce_percentage: 6.02745618307040320615897144307382404804229736328125
        workers:
        - duration: 5.962133916683182377482808078639209270477294921875
          day_percentage: 5.63737665663332876420099637471139430999755859375
          name: name
          id: id
        - duration: 5.962133916683182377482808078639209270477294921875
          day_percentage: 5.63737665663332876420099637471139430999755859375
          name: name
          id: id
    inline_response_200_12:
      type: object
      properties:
        name:
          type: string
          description: returns abbreviated name of work zone
        id:
          type: string
          description: returns 6-digit ID of AO-1 Work Zone Tag
        total_time:
          type: number
          description: "returns in minutes, total time spent in work zone for selected\
            \ date"
        location:
          type: array
          description: returns complete location description of work zone
          items:
            type: string
            description: returns location parameter
        hazards:
          type: array
          description: returns risk factors present in work zone
          items:
            type: string
            description: returns risk factor
        ppe:
          type: array
          description: returns required PPE in work zone
          items:
            type: string
            description: returns PPE requirement
        certifications:
          type: array
          description: returns required certifications in work zone
          items:
            type: string
            description: returns certification requirement
        production:
          type: array
          description: returns production objectives in work zone
          items:
            $ref: '#/components/schemas/projectszones_production'
        traffic:
          type: array
          items:
            $ref: '#/components/schemas/projectszones_traffic'
      example:
        hazards:
        - hazards
        - hazards
        ppe:
        - ppe
        - ppe
        production:
        - activity_name: activity_name
          company_id: company_id
          activity_id: activity_id
          activity_rate: 6.02745618307040320615897144307382404804229736328125
          cost_code: cost_code
        - activity_name: activity_name
          company_id: company_id
          activity_id: activity_id
          activity_rate: 6.02745618307040320615897144307382404804229736328125
          cost_code: cost_code
        name: name
        location:
        - location
        - location
        id: id
        total_time: 0.80082819046101150206595775671303272247314453125
        certifications:
        - certifications
        - certifications
        traffic:
        - name: name
          id: id
          total_time: 1.46581298050294517310021547018550336360931396484375
          workers:
          - name: name
            id: id
            total_time: 5.962133916683182377482808078639209270477294921875
          - name: name
            id: id
            total_time: 5.962133916683182377482808078639209270477294921875
        - name: name
          id: id
          total_time: 1.46581298050294517310021547018550336360931396484375
          workers:
          - name: name
            id: id
            total_time: 5.962133916683182377482808078639209270477294921875
          - name: name
            id: id
            total_time: 5.962133916683182377482808078639209270477294921875
    body:
      required:
      - grant_type
      type: object
      properties:
        grant_type:
          type: string
        refresh_token:
          type: string
    body_3:
      required:
      - company
      - email
      - first
      - last
      type: object
      properties:
        company:
          type: string
          description: Company ID
        first:
          type: string
          description: First name
        last:
          type: string
          description: Last name
        email:
          type: string
          description: Email
        mount_id:
          type: string
          description: 6-digit mount ID assigned to user (optional)
    body_4:
      required:
      - company
      - first
      - last
      - phone
      type: object
      properties:
        first:
          type: string
          description: Worker first name
        last:
          type: string
          description: Worker last name
        phone:
          type: string
          description: "Worker phone (formatted: '+##########')"
        company:
          type: string
          description: Company ID
        mount_id:
          type: string
          description: Mount ID assignment (optional)
    body_1:
      required:
      - address_1
      - address_2
      - city
      - country
      - end
      - name
      - start
      - state
      - zip
      type: object
      properties:
        name:
          type: string
          description: Project name
        address_1:
          type: string
          description: "Project address, primary"
        address_2:
          type: string
          description: "Project address, secondary"
        city:
          type: string
          description: Project city
        state:
          type: string
          description: Project state (2-character code)
        zip:
          type: string
          description: Project zip code
        country:
          type: string
          description: Project country
        start:
          type: integer
          description: Unix timestamp representing project start date
        end:
          type: integer
          description: Unix timestamp representing project end date
    body_2:
      required:
      - address_1
      - address_2
      - city
      - country
      - name
      - phone
      - state
      - zip
      type: object
      properties:
        name:
          type: string
          description: Company name
        address_1:
          type: string
          description: "Company address, primary"
        address_2:
          type: string
          description: "Company address, secondary"
        city:
          type: string
          description: Company city
        state:
          type: string
          description: Company state (2-character code)
        zip:
          type: string
          description: Company zip
        country:
          type: string
          description: Company country
        phone:
          type: string
          description: "Company phone (formatted: '+##########')"
    projectsprojectusers_company:
      type: object
      properties:
        name:
          type: string
          description: Name of user company
        id:
          type: string
          description: Unique ID of user company
      example:
        name: name
        id: id
    inline_response_200:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        token_type:
          type: string
        expires:
          type: integer
      example:
        access_token: access_token
        refresh_token: refresh_token
        expires: 0
        token_type: token_type
    body_7:
      required:
      - client
      - date
      - project
      type: object
      properties:
        client:
          type: string
          description: Client ID
        project:
          type: string
          description: Project ID
        date:
          type: string
          description: "Date, formatted YYYY-MM-DD"
    body_8:
      required:
      - client
      - date
      - project
      type: object
      properties:
        client:
          type: string
          description: Client ID
        project:
          type: string
          description: Project ID
        date:
          type: string
          description: "Date, formatted YYYY-MM-DD"
    body_5:
      required:
      - client
      - date
      - project
      type: object
      properties:
        client:
          type: string
          description: Client ID
        project:
          type: string
          description: Project ID
        date:
          type: string
          description: "Date, formatted YYYY-MM-DD"
    body_6:
      required:
      - client
      - date
      - project
      type: object
      properties:
        client:
          type: string
          description: Client ID
        project:
          type: string
          description: Project ID
        date:
          type: string
          description: "Date, formatted YYYY-MM-DD"
    inline_response_200_9:
      type: object
      properties:
        name:
          type: string
          description: returns name of subcontractor
        id:
          type: string
          description: returns unique ID of subcontractor
        on_site:
          type: boolean
          description: "returns true if subcontractor has workers on site, false if\
            \ not"
        headcount:
          type: integer
          description: returns total subcontractor headcount
        arrival_local:
          type: string
          description: "returns average subcontractor arrival time, formatted in a\
            \ localized h:mm PM timestamp"
        arrival_unix:
          type: integer
          description: "returns average subcontractor arrival time, formatted as a\
            \ unix timestamp"
        workers:
          type: array
          items:
            $ref: '#/components/schemas/projectstimecards_workers'
      example:
        headcount: 0
        name: name
        id: id
        arrival_local: arrival_local
        workers:
        - duration: 5.63737665663332876420099637471139430999755859375
          exit_local: exit_local
          exit_unix: 5
          name: name
          id: id
          arrival_local: arrival_local
          on_site: true
          arrival_unix: 1
        - duration: 5.63737665663332876420099637471139430999755859375
          exit_local: exit_local
          exit_unix: 5
          name: name
          id: id
          arrival_local: arrival_local
          on_site: true
          arrival_unix: 1
        on_site: true
        arrival_unix: 6
    projectszones_production:
      type: object
      properties:
        activity_id:
          type: string
          description: returns production objective activity ID
        activity_name:
          type: string
          description: returns production objective activity name
        activity_rate:
          type: number
          description: returns production objective expected units per hour
        company_id:
          type: string
          description: returns unique company ID if production objective is restricted
            to a specific subcontractor
        cost_code:
          type: string
          description: returns production objective cost code
      example:
        activity_name: activity_name
        company_id: company_id
        activity_id: activity_id
        activity_rate: 6.02745618307040320615897144307382404804229736328125
        cost_code: cost_code
    projectstimecards_workers:
      type: object
      properties:
        name:
          type: string
          description: returns worker's full name
        id:
          type: string
          description: returns unique ID of worker
        on_site:
          type: boolean
          description: "returns true if worker is on site, false if not"
        arrival_local:
          type: string
          description: "returns worker arrival time, formatted in a localized h:mm\
            \ PM timestamp"
        arrival_unix:
          type: integer
          description: "returns worker arrival time, formatted as a unix timestamp"
        exit_local:
          type: string
          description: "returns worker exit time, formatted in a localized h:mm PM\
            \ timestamp, or \"\" if worker is still on site"
        exit_unix:
          type: integer
          description: "returns worker exit time, formatted as a unix timestamp, or\
            \ 0 if worker is still on site"
        duration:
          type: number
          description: "returns in minutes, current duration of worker's time on site,\
            \ or total time on site if currently off site"
      example:
        duration: 5.63737665663332876420099637471139430999755859375
        exit_local: exit_local
        exit_unix: 5
        name: name
        id: id
        arrival_local: arrival_local
        on_site: true
        arrival_unix: 1
    inline_response_200_11_subcontractors:
      type: object
      properties:
        name:
          type: string
          description: returns name of subcontractor
        id:
          type: string
          description: returns unique id of subcontractor
        headcount:
          type: integer
          description: returns total headcount of subcontractor for selected date
        change:
          type: number
          description: returns percentage difference in total headcount of subcontractor
            relative to previous date
        trend:
          type: string
          description: returns trend of percentage difference in total headcount of
            subcontractor relative to previous date
        workers:
          type: array
          items:
            $ref: '#/components/schemas/inline_response_200_11_workers'
      example:
        headcount: 6
        trend: trend
        change: 1.46581298050294517310021547018550336360931396484375
        name: name
        id: id
        workers:
        - name: name
          id: id
          arrival_local: arrival_local
          on_site: true
          arrival_unix: 5
        - name: name
          id: id
          arrival_local: arrival_local
          on_site: true
          arrival_unix: 5
    inline_response_200_5:
      type: object
      properties:
        name:
          type: string
          description: User full name
        id:
          type: string
          description: User ID
        first:
          type: string
          description: User first name
        last:
          type: string
          description: User last name
        initials:
          type: string
          description: User initials
        cell_phone:
          type: string
          description: User cell phone
        email:
          type: string
          description: User email
        city:
          type: string
          description: User city
        state:
          type: string
          description: User state
        zip:
          type: string
          description: User zip code
        country:
          type: string
          description: User country
        created:
          type: integer
          description: Unix timestamp representing user creation date
        logged_in:
          type: boolean
          description: Indicates whether the added user has completed account creation
        assigned_mount:
          type: boolean
          description: Indicates whether the added user was assigned a mount ID
        mount_id:
          type: string
          description: Assigned mount ID (if assigned)
        company:
          $ref: '#/components/schemas/projectsprojectusers_company'
        permissions:
          $ref: '#/components/schemas/projectsprojectusers_permissions'
      example:
        zip: zip
        country: country
        assigned_mount: true
        last: last
        city: city
        initials: initials
        created: 0
        logged_in: true
        cell_phone: cell_phone
        permissions:
          dashboard_access:
          - dashboard_access
          - dashboard_access
          company_only_visibility: true
          anonymized_individuals: true
        name: name
        company:
          name: name
          id: id
        id: id
        state: state
        first: first
        email: email
        mount_id: mount_id
    inline_response_200_6:
      type: object
      properties:
        success:
          type: boolean
          description: returns success indication of user addition
        id:
          type: string
          description: returns unique ID of added user
      example:
        success: true
        id: id
    inline_response_200_7:
      type: object
      properties:
        name:
          type: string
          description: Worker full name
        id:
          type: string
          description: Worker ID
        first:
          type: string
          description: Worker first name
        last:
          type: string
          description: Worker last name
        initials:
          type: string
          description: Worker initials
        cell_phone:
          type: string
          description: Worker cell phone
        email:
          type: string
          description: Worker email
        city:
          type: string
          description: Worker city
        state:
          type: string
          description: Worker state
        zip:
          type: string
          description: Worker zip code
        country:
          type: string
          description: Worker country
        created:
          type: integer
          description: Unix timestamp representing worker creation date
        assigned_mount:
          type: boolean
          description: Indicates whether the added user was assigned a mount ID
        mount_id:
          type: string
          description: Assigned mount ID (if assigned)
        last_seen:
          type: integer
          description: Unix timestamp representing last sensor touch-point (shift
            start or shift end). Returns 0 if no shifts have been logged yet
        on_site:
          type: boolean
          description: Indicates whether the worker is currently on site
        company:
          $ref: '#/components/schemas/projectsprojectusers_company'
      example:
        zip: zip
        country: country
        assigned_mount: true
        last: last
        last_seen: 6
        city: city
        initials: initials
        created: 0
        cell_phone: cell_phone
        name: name
        company:
          name: name
          id: id
        id: id
        state: state
        first: first
        email: email
        mount_id: mount_id
        on_site: true
    inline_response_200_11_workers:
      type: object
      properties:
        name:
          type: string
          description: returns worker's full name
        id:
          type: string
          description: returns unique ID of worker
        on_site:
          type: boolean
          description: "returns true if worker is on site, false if not"
        arrival_local:
          type: string
          description: "returns worker arrival time, formatted in a localized h:mm\
            \ PM timestamp"
        arrival_unix:
          type: integer
          description: "returns worker arrival time, formatted as a unix timestamp"
      example:
        name: name
        id: id
        arrival_local: arrival_local
        on_site: true
        arrival_unix: 5
    inline_response_200_8:
      type: object
      properties:
        success:
          type: boolean
          description: returns success indication of worker addition
        id:
          type: string
          description: returns unique ID of added worker
      example:
        success: true
        id: id
    projectszones_workers:
      type: object
      properties:
        name:
          type: string
          description: returns name of worker
        id:
          type: string
          description: returns unique ID of worker
        total_time:
          type: number
          description: "returns in minutes, total duration of time spent in work zone\
            \ for selected date"
      example:
        name: name
        id: id
        total_time: 5.962133916683182377482808078639209270477294921875
    projectszones_traffic:
      type: object
      properties:
        name:
          type: string
          description: returns name of subcontractor
        id:
          type: string
          description: returns unique ID of subcontractor
        total_time:
          type: number
          description: "returns in minutes, total duration of time spent in work zone\
            \ for selected date"
        workers:
          type: array
          items:
            $ref: '#/components/schemas/projectszones_workers'
      example:
        name: name
        id: id
        total_time: 1.46581298050294517310021547018550336360931396484375
        workers:
        - name: name
          id: id
          total_time: 5.962133916683182377482808078639209270477294921875
        - name: name
          id: id
          total_time: 5.962133916683182377482808078639209270477294921875
    projectsprojectusers_permissions:
      type: object
      properties:
        anonymized_individuals:
          type: boolean
          description: Permission indicating access to anonymized-only data sets
        company_only_visibility:
          type: boolean
          description: Permission indicating limited access to company-specific data
        dashboard_access:
          type: array
          description: Permission indicating dashboard access within the WorkerSense®
            web platform
          items:
            type: string
            description: Returns accessible dashboard
      example:
        dashboard_access:
        - dashboard_access
        - dashboard_access
        company_only_visibility: true
        anonymized_individuals: true
    inline_response_200_1:
      type: object
      properties:
        client:
          type: string
          description: Client ID
        project:
          type: string
          description: Project ID
        name:
          type: string
          description: Name of project
        city:
          type: string
          description: City of project location
        state:
          type: string
          description: State of project location
        lon:
          type: number
          description: Longitude coordinate of project centroid
        lat:
          type: number
          description: Latitude coordinate of project centroid
        progression:
          type: number
          description: Project progression percentage
        start:
          type: integer
          description: UNIX timestamp representing project start date
      example:
        city: city
        name: name
        start: 5
        client: client
        project: project
        progression: 1.46581298050294517310021547018550336360931396484375
        lon: 0.80082819046101150206595775671303272247314453125
        state: state
        lat: 6.02745618307040320615897144307382404804229736328125
    inline_response_200_2:
      type: object
      properties:
        success:
          type: boolean
          description: returns success indication of project creation
        id:
          type: string
          description: returns unique ID of created project
      example:
        success: true
        id: id
    inline_response_200_3:
      type: object
      properties:
        name:
          type: string
          description: Company name
        id:
          type: string
          description: Company ID
        address_1:
          type: string
          description: "Company address, primary"
        address_2:
          type: string
          description: "Company address, secondary"
        city:
          type: string
          description: Company city
        state:
          type: string
          description: Company state
        zip:
          type: string
          description: Company zip
        country:
          type: string
          description: Company country
        phone:
          type: string
          description: Company phone
      example:
        zip: zip
        country: country
        city: city
        phone: phone
        address_1: address_1
        address_2: address_2
        name: name
        id: id
        state: state
    inline_response_200_4:
      type: object
      properties:
        success:
          type: boolean
          description: returns success indication of company creation
        id:
          type: string
          description: returns unique ID of created company
      example:
        success: true
        id: id
  securitySchemes:
    BasicAuth:
      type: http
      description: Provide Email and Password
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
